{
  "comments": [
    {
      "key": {
        "uuid": "c483a33b_010e75bb",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 15,
      "author": {
        "id": 1000427
      },
      "writtenOn": "2021-09-22T04:29:47Z",
      "side": 1,
      "message": "In case?",
      "range": {
        "startLine": 15,
        "startChar": 58,
        "endLine": 15,
        "endChar": 64
      },
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "1623e350_8a41186e",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 16,
      "author": {
        "id": 1000427
      },
      "writtenOn": "2021-09-22T04:29:47Z",
      "side": 1,
      "message": "typo?",
      "range": {
        "startLine": 16,
        "startChar": 29,
        "endLine": 16,
        "endChar": 38
      },
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "fd940efc_5c2b46fc",
        "filename": "extensions/phal/phal_error.cpp",
        "patchSetId": 3
      },
      "lineNbr": 515,
      "author": {
        "id": 1000004
      },
      "writtenOn": "2021-09-21T20:35:18Z",
      "side": 1,
      "message": "I must have missed this. phal has it\u0027s own trace log??",
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "b3969513_8821208c",
        "filename": "extensions/phal/phal_error.cpp",
        "patchSetId": 3
      },
      "lineNbr": 515,
      "author": {
        "id": 1000086
      },
      "writtenOn": "2021-09-23T10:09:10Z",
      "side": 1,
      "message": "Refer line 202 in this file.\nphal libraries provides callback mechansim log required debug level traces. This thi trace log captured as part of call back functions.",
      "parentUuid": "fd940efc_5c2b46fc",
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "8442feef_7144063d",
        "filename": "extensions/phal/phal_error.cpp",
        "patchSetId": 3
      },
      "lineNbr": 557,
      "author": {
        "id": 1000427
      },
      "writtenOn": "2021-09-22T04:29:47Z",
      "side": 1,
      "message": "Extra new line?",
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "3282ccbe_35efc173",
        "filename": "extensions/phal/phal_error.cpp",
        "patchSetId": 3
      },
      "lineNbr": 557,
      "author": {
        "id": 1000086
      },
      "writtenOn": "2021-09-23T10:09:10Z",
      "side": 1,
      "message": "Ack",
      "parentUuid": "8442feef_7144063d",
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "bb11b67b_f206e753",
        "filename": "extensions/phal/phal_error.cpp",
        "patchSetId": 3
      },
      "lineNbr": 577,
      "author": {
        "id": 1000427
      },
      "writtenOn": "2021-09-22T04:29:47Z",
      "side": 1,
      "message": "This API is possible to throw an exception, do we need to handle that? I am wondering since this FFDC collection (collect possible debug data).",
      "range": {
        "startLine": 577,
        "startChar": 48,
        "endLine": 577,
        "endChar": 57
      },
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "4e082392_7ba6a64d",
        "filename": "extensions/phal/phal_error.cpp",
        "patchSetId": 3
      },
      "lineNbr": 577,
      "author": {
        "id": 1000086
      },
      "writtenOn": "2021-09-23T10:09:10Z",
      "side": 1,
      "message": "Since already validated pdbg target, index is going to return integer value. and chances of exception is low.",
      "parentUuid": "bb11b67b_f206e753",
      "range": {
        "startLine": 577,
        "startChar": 48,
        "endLine": 577,
        "endChar": 57
      },
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "67352dad_d98b5d57",
        "filename": "meson.build",
        "patchSetId": 3
      },
      "lineNbr": 94,
      "author": {
        "id": 1000004
      },
      "writtenOn": "2021-09-21T20:35:18Z",
      "side": 1,
      "message": "formatting issue",
      "revId": "62f4f3c24d92d98cb7684881da5257eeed9daf7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}